server:
  port: 8081
auditor:
  user: "NY-dev"
key: "2B4D6251655468566D597133743677397A24432646294A404E635266556A586E"
#jasypt:
#  encryptor:
#    password: { $JASYPT_ENCRYPTOR_PASSWORD: }


spring:
  application:
    name: user
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    initialize: true
    username: ENC(7Kba8/Aec0xYe3zart1h8hkyRZzUc66kZOZC945asu1XSSwrwn3c4SZpNLwZ2NGhRcwXElomlvdImL7XbG9ANg==)
    password: ENC(o731Rsah1Liw1u6CUEYwgc/0iNBMxlcR06/v4JgfGwaJRIYGrS+CkHMe8gEdJp6vkOWU8V0XrHuzebxpi1SGEQ==)
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.databaseName}
    dockerContainerName: postgresqldb
    host: 172.17.0.2
    localhost: localhost
    port: 5432
    databaseName: dealershipdb
