server:
  port: 8081

spring:
  application:

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    name: customer
    hibernate:
      ddl-auto: create
    show-sql: true
      #          hbm2ddl: create
    #      generate-ddl: true
  datasource:
#    initialization-mode: always
#    platform: postgresql
    initialize: true
#    schema: dealershipdb
    username: postgres
    password: 1234
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.databaseName}
    dockerContainerName: postgresqldb
    host: 172.17.0.2
    localhost: localhost
    port: 5432
    databaseName: dealershipdb

  auditor:
    user: "NY-dev"