apiVersion: apps/v1
kind: Deployment
metadata :
  name: k8-com.cars.service-dealership
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8-com.cars.service-dealership
  template:
    metadata:
      labels:
        app: k8-com.cars.service-dealership
    spec:
      containers:
        - name: com.cars.service-dealership
          image: com.cars.service-dealership:latest
          imagePullPolicy: Never